export interface ProIndustry {
  slug: string;
  name: string;
  emoji: string;
  category: "Trades" | "Cleaning" | "Outdoor" | "Specialty";
  tagline: string;
  desc: string;
  heroLine1: string;
  heroLine2: string;
  badge: string;
  features: { title: string; desc: string; icon: string }[];
  steps: { num: string; title: string; desc: string }[];
  faqs: { q: string; a: string }[];
  testimonial: { quote: string; name: string; business: string; location: string };
  compareRows: [string, boolean, boolean][];
}

export const PRO_INDUSTRIES: ProIndustry[] = [
  {
    slug: "hvac",
    name: "HVAC",
    emoji: "❄️",
    category: "Trades",
    tagline: "Service calls. Covered.",
    desc: "From emergency dispatch to seasonal tune-ups, Certxa keeps your HVAC business running year-round.",
    heroLine1: "Your HVAC Business,",
    heroLine2: "Always at Full Capacity.",
    badge: "Built for HVAC Contractors",
    features: [
      { icon: "📅", title: "Online Booking & Dispatch",    desc: "Customers book service calls 24/7. Jobs route to your nearest available tech automatically." },
      { icon: "📄", title: "Service Agreements",           desc: "Sell annual maintenance plans, auto-bill customers, and track agreement renewals." },
      { icon: "🔧", title: "Equipment History Tracking",  desc: "Log make, model, and serial number for every system. Pull history on any service call." },
      { icon: "💳", title: "Mobile Invoicing & Payment",   desc: "Send invoices from the job site and collect payment by card, cash, or bank transfer on the spot." },
    ],
    steps: [
      { num: "01", title: "Set Up Your Services",  desc: "Add your service catalog — tune-ups, repairs, installations — with flat-rate or hourly pricing." },
      { num: "02", title: "Dispatch Your Techs",   desc: "Drag jobs onto your tech's schedule. They get instant notifications with job details and directions." },
      { num: "03", title: "Get Paid on the Job",   desc: "Techs invoice on-site, customers pay instantly. Money hits your account same day." },
    ],
    faqs: [
      { q: "Can I manage maintenance contracts?",    a: "Yes — create recurring service agreements with auto-billing, renewal reminders, and full service history per agreement." },
      { q: "Does it work for multi-tech operations?", a: "Certxa is built for teams. Assign jobs, track GPS location, and see every tech's schedule in one view." },
    ],
    testimonial: { quote: "We went from 12 calls a week to 35. The online booking alone paid for the software in the first month.", name: "Marcus T.", business: "TempRight HVAC", location: "Dallas, TX" },
    compareRows: [
      ["Online customer booking",           true, false],
      ["Equipment history per customer",    true, false],
      ["Service agreement auto-billing",    true, false],
      ["Mobile invoicing from job site",    true, false],
      ["GPS-based tech dispatch",           true, false],
      ["Automated review requests",         true, false],
    ],
  },
  {
    slug: "plumbing",
    name: "Plumbing",
    emoji: "🔧",
    category: "Trades",
    tagline: "Every call. On time.",
    desc: "Handle emergency dispatch, itemized invoicing, and job-site photos — all from one app built for plumbers.",
    heroLine1: "Every Call Taken.",
    heroLine2: "Every Job Billed.",
    badge: "Built for Plumbing Contractors",
    features: [
      { icon: "🚨", title: "Emergency Dispatch",         desc: "Flag jobs as emergency, notify the nearest available tech, and get an ETA to the customer instantly." },
      { icon: "📋", title: "Itemized Invoicing",         desc: "Add parts, labor, and fees line by line. Customers see exactly what they're paying for." },
      { icon: "📷", title: "Job-Site Photo Logs",        desc: "Techs capture before/after photos that attach automatically to the job record." },
      { icon: "🔁", title: "Repeat Customer Tracking",   desc: "See full service history for every address — what was done, who did it, and what it cost." },
    ],
    steps: [
      { num: "01", title: "Capture Every Lead",    desc: "Customers book online or call in. Every request lands in your dispatch queue instantly." },
      { num: "02", title: "Dispatch & Track",      desc: "Assign jobs to techs, monitor arrival times, and message customers automatically." },
      { num: "03", title: "Invoice & Collect",     desc: "Create itemized invoices on-site with parts and labor. Accept payment before you leave the job." },
    ],
    faqs: [
      { q: "Can I track parts inventory?",           a: "Yes — add parts to jobs from your inventory list. Stock levels update automatically as parts are used." },
      { q: "How does emergency dispatch work?",       a: "Mark a job as 'emergency' in the app. Certxa sends an alert to available techs and notifies the customer with an ETA." },
    ],
    testimonial: { quote: "We stopped losing emergency calls to competitors. The dispatch feature routes jobs to whoever's closest — it's a game changer.", name: "Dana R.", business: "Riverline Plumbing", location: "Chicago, IL" },
    compareRows: [
      ["Online & phone booking capture",    true, false],
      ["Emergency dispatch flagging",       true, false],
      ["Itemized parts + labor invoicing",  true, false],
      ["Before/after photo logging",        true, false],
      ["Full address service history",      true, false],
      ["Automatic review collection",       true, false],
    ],
  },
  {
    slug: "electrical",
    name: "Electrical",
    emoji: "⚡",
    category: "Trades",
    tagline: "Wired for growth.",
    desc: "Online booking, permit notes, on-site quoting, and crew management — built for electrical contractors.",
    heroLine1: "More Jobs Won.",
    heroLine2: "Less Paperwork.",
    badge: "Built for Electrical Contractors",
    features: [
      { icon: "📐", title: "On-Site Quoting",           desc: "Build and send professional quotes from your phone before you leave the property. Customers approve instantly." },
      { icon: "📝", title: "Permit & Code Notes",       desc: "Attach permit numbers, inspection dates, and code notes to every job for complete compliance records." },
      { icon: "👷", title: "Crew Job Assignment",       desc: "Split large jobs across multiple electricians. Each crew member sees their portion of the work." },
      { icon: "💰", title: "Draw-Based Billing",        desc: "Bill in milestones for larger projects. Request deposits and progress payments automatically." },
    ],
    steps: [
      { num: "01", title: "Quote the Job",       desc: "Build a detailed quote on-site with labor, materials, and fees. Send it for digital approval in seconds." },
      { num: "02", title: "Schedule the Work",   desc: "Assign crews, set timeline milestones, and attach permit info. Everyone stays on the same page." },
      { num: "03", title: "Collect Payment",     desc: "Bill in draws or on completion. Accept credit cards, ACH, or check from any device." },
    ],
    faqs: [
      { q: "Can I manage multi-phase projects?",  a: "Yes — break large electrical projects into phases with separate schedules, crews, and billing milestones." },
      { q: "Does Certxa store permit info?",      a: "Absolutely. Attach permit numbers, jurisdiction notes, and inspection dates to any job for your records." },
    ],
    testimonial: { quote: "The quoting tool closes deals on the spot. Customers see the price, approve it on their phone, and we start the next day.", name: "Jess P.", business: "Powerline Electric", location: "Atlanta, GA" },
    compareRows: [
      ["On-site quote generation",          true, false],
      ["Permit & compliance note logging",  true, false],
      ["Multi-crew job splitting",          true, false],
      ["Milestone-based billing",           true, false],
      ["Customer digital approval",         true, false],
      ["Automated review requests",         true, false],
    ],
  },
  {
    slug: "roofing",
    name: "Roofing",
    emoji: "🏠",
    category: "Trades",
    tagline: "Close more estimates.",
    desc: "Roof-specific estimating, material tracking, insurance claim support, and crew scheduling for roofers.",
    heroLine1: "More Roofs.",
    heroLine2: "More Revenue.",
    badge: "Built for Roofing Contractors",
    features: [
      { icon: "📐", title: "Roof Estimation Tool",       desc: "Build accurate estimates with square footage, materials, and labor. Send branded proposals in minutes." },
      { icon: "🏗️", title: "Material Tracking",         desc: "Log shingles, underlayment, and supplies per job. Track what's on-site and what's been used." },
      { icon: "📋", title: "Insurance Claim Support",    desc: "Attach claim numbers, adjuster notes, and photos to jobs. Keep all documentation in one place." },
      { icon: "☀️", title: "Storm Lead Follow-Up",      desc: "Tag leads from storm events and auto-send follow-up messages to convert estimates faster." },
    ],
    steps: [
      { num: "01", title: "Estimate On-Site",   desc: "Calculate roof size, select materials, and generate a professional estimate on your tablet or phone." },
      { num: "02", title: "Schedule the Crew",  desc: "Assign your roofing crew, set start dates, and manage material delivery timing from the app." },
      { num: "03", title: "Invoice & Get Paid", desc: "Collect a deposit upfront, then final payment on completion. All tracked and recorded automatically." },
    ],
    faqs: [
      { q: "Can I manage insurance jobs?",       a: "Yes — attach claim numbers and adjuster info to any job. Documents and photos are stored for easy reference during claim processing." },
      { q: "How does storm lead management work?", a: "Tag leads from storm events, and Certxa helps you send automatic follow-ups to keep your estimates top of mind." },
    ],
    testimonial: { quote: "We used to lose half our storm leads to follow-up failures. Now the app sends reminders and we close 3x more of our estimates.", name: "Chris N.", business: "StormShield Roofing", location: "Oklahoma City, OK" },
    compareRows: [
      ["Roof-specific estimation",          true, false],
      ["Material tracking per job",         true, false],
      ["Insurance claim documentation",     true, false],
      ["Storm lead auto-follow-up",         true, false],
      ["Deposit + final payment billing",   true, false],
      ["Crew scheduling & dispatch",        true, false],
    ],
  },
  {
    slug: "pest-control",
    name: "Pest Control",
    emoji: "🪲",
    category: "Specialty",
    tagline: "Recurring routes. Automated.",
    desc: "Route scheduling, chemical usage logs, subscription billing, and automated retreat reminders — built for pest control.",
    heroLine1: "Your Routes.",
    heroLine2: "Running Themselves.",
    badge: "Built for Pest Control Businesses",
    features: [
      { icon: "🗺️", title: "Route Optimization",        desc: "Organize technician routes by geography. Stop double-booking and wasted drive time." },
      { icon: "🧪", title: "Chemical Usage Logging",     desc: "Record pesticide type, amount used, and target pests per visit for compliance documentation." },
      { icon: "🔄", title: "Subscription Billing",       desc: "Auto-bill monthly or quarterly treatment plans. Customers never miss a payment." },
      { icon: "🔔", title: "Retreat Reminders",          desc: "Send automatic reminders when a guarantee period is approaching to re-book service." },
    ],
    steps: [
      { num: "01", title: "Set Up Your Routes",  desc: "Group recurring customers by area. Certxa optimizes the daily route for each tech." },
      { num: "02", title: "Log Every Treatment", desc: "Check in on-site, record chemicals used, and add service notes. All stored automatically." },
      { num: "03", title: "Bill Automatically",  desc: "Subscription customers are billed on schedule. No manual invoicing. No late payments." },
    ],
    faqs: [
      { q: "Can I track chemical usage for compliance?", a: "Yes — log every chemical application with product, quantity, and target pest. Pull compliance reports on demand." },
      { q: "How do subscriptions work?",                  a: "You set the schedule and price. Certxa auto-bills and auto-schedules each recurring visit without any manual work." },
    ],
    testimonial: { quote: "I stopped spending Saturday afternoons doing invoices. The subscription billing handles everything automatically.", name: "Leticia M.", business: "GreenShield Pest", location: "Phoenix, AZ" },
    compareRows: [
      ["Route optimization",               true, false],
      ["Chemical log for compliance",      true, false],
      ["Auto-billing subscriptions",       true, false],
      ["Retreat & re-book reminders",      true, false],
      ["Online booking for new customers", true, false],
      ["Automated review collection",      true, false],
    ],
  },
  {
    slug: "pool-service",
    name: "Pool Service",
    emoji: "🏊",
    category: "Specialty",
    tagline: "Weekly routes. On autopilot.",
    desc: "Weekly route scheduling, chemical readings, service history, and auto-billing for pool service businesses.",
    heroLine1: "Clean Pools.",
    heroLine2: "Clean Books.",
    badge: "Built for Pool Service Companies",
    features: [
      { icon: "🗺️", title: "Weekly Route Scheduling",   desc: "Assign pools to technicians by day and geography. Routes auto-populate each week." },
      { icon: "🧪", title: "Chemical Reading Logs",      desc: "Record chlorine, pH, and chemical readings per visit. Flag pools that need attention." },
      { icon: "📸", title: "Service Photo Capture",      desc: "Photograph pool condition before and after service. Customers get a summary with every visit." },
      { icon: "💳", title: "Auto-Recurring Billing",     desc: "Monthly service plans billed automatically. No invoicing, no chasing payments." },
    ],
    steps: [
      { num: "01", title: "Build Your Routes",  desc: "Add your customers and assign them to technicians. Routes are organized by day and area automatically." },
      { num: "02", title: "Log Every Visit",    desc: "Check in, log chemical readings, take photos, and leave service notes — all in 60 seconds." },
      { num: "03", title: "Get Paid Monthly",   desc: "Monthly service fees bill automatically on your schedule. No manual invoicing required." },
    ],
    faqs: [
      { q: "Can customers see their service history?",  a: "Yes — customers can view a log of every visit, reading, and photo taken at their pool through their client portal." },
      { q: "How do I handle one-time repairs?",         a: "Add repair jobs alongside recurring service. Bill separately or roll into the monthly invoice — your choice." },
    ],
    testimonial: { quote: "My routes are fully automated. I wake up, the techs know where to go, and the customers get billed without me touching anything.", name: "Omar S.", business: "Crystal Clear Pool Co.", location: "Tampa, FL" },
    compareRows: [
      ["Auto-weekly route scheduling",     true, false],
      ["Chemical reading logs per visit",  true, false],
      ["Before/after service photos",      true, false],
      ["Auto-recurring monthly billing",   true, false],
      ["Customer visit summaries",         true, false],
      ["One-time repair billing",          true, false],
    ],
  },
  {
    slug: "house-cleaning",
    name: "House Cleaning",
    emoji: "🏠",
    category: "Cleaning",
    tagline: "Book it. Clean it. Done.",
    desc: "Recurring bookings, team scheduling, supplies tracking, and instant invoicing for house cleaning businesses.",
    heroLine1: "Your Cleaning Business.",
    heroLine2: "Running Spotlessly.",
    badge: "Built for House Cleaning Businesses",
    features: [
      { icon: "📅", title: "Recurring Booking Management", desc: "Set weekly, biweekly, or monthly schedules per customer. Recurring jobs auto-populate your calendar." },
      { icon: "👩‍👩‍👧", title: "Team Scheduling",             desc: "Assign crews to jobs, track who's available, and prevent double-booking across your whole team." },
      { icon: "📋", title: "Cleaning Checklists",            desc: "Attach a checklist to each job. Cleaners check off tasks on their phone as they complete them." },
      { icon: "💳", title: "Auto-Pay After Each Visit",     desc: "Charge the card on file automatically when the job is marked complete. No awkward payment collection." },
    ],
    steps: [
      { num: "01", title: "Book the Client",    desc: "New clients book online with their cleaning type, home size, and preferred schedule." },
      { num: "02", title: "Assign the Crew",    desc: "Certxa schedules recurring jobs automatically. Your crew gets notified with the address and checklist." },
      { num: "03", title: "Collect on Autopilot", desc: "The card on file is charged when the job is marked done. Receipts go out automatically." },
    ],
    faqs: [
      { q: "Can I manage multiple cleaning teams?",   a: "Yes — add unlimited team members, set their availability, and Certxa handles scheduling across all crews." },
      { q: "What if a customer wants to skip a week?", a: "Customers can reschedule or skip through their client portal. You'll see the change in your calendar instantly." },
    ],
    testimonial: { quote: "I used to spend two hours every Sunday scheduling. Now I do it in 10 minutes. The recurring booking feature changed everything.", name: "Amara W.", business: "Shine Right Cleaning", location: "Nashville, TN" },
    compareRows: [
      ["Online recurring booking",          true, false],
      ["Team availability scheduling",      true, false],
      ["Digital cleaning checklists",       true, false],
      ["Auto-charge card after service",    true, false],
      ["Customer self-service portal",      true, false],
      ["Automated review requests",         true, false],
    ],
  },
  {
    slug: "carpet-cleaning",
    name: "Carpet Cleaning",
    emoji: "🧹",
    category: "Cleaning",
    tagline: "Quote by room. Bill fast.",
    desc: "Room-by-room booking, add-on upsells, annual re-booking, and mobile invoicing for carpet cleaning businesses.",
    heroLine1: "Every Room Booked.",
    heroLine2: "Every Job Paid.",
    badge: "Built for Carpet Cleaning Businesses",
    features: [
      { icon: "🛋️", title: "Room-by-Room Booking",    desc: "Customers select the rooms they need cleaned when booking online. Pricing updates automatically." },
      { icon: "✨", title: "Add-On Upsells",           desc: "Offer pet odor treatment, scotch-guard, and upholstery cleaning as easy add-ons during booking." },
      { icon: "🔁", title: "Annual Re-Booking",        desc: "Certxa sends re-booking reminders at your set interval — 6 months, 12 months, whatever you choose." },
      { icon: "📱", title: "Mobile Invoice on Arrival", desc: "Walk in, check the job details, and send the invoice before you start. Get paid before you leave." },
    ],
    steps: [
      { num: "01", title: "Accept Bookings Online",  desc: "Customers pick rooms, select add-ons, and book a time slot that works for their schedule." },
      { num: "02", title: "Do the Job",              desc: "Your tech arrives with the job sheet on their phone — room count, add-ons, and access notes." },
      { num: "03", title: "Invoice & Collect",        desc: "Invoice from the app in 30 seconds. Collect card, cash, or tap-to-pay on the spot." },
    ],
    faqs: [
      { q: "Can I charge different rates per room type?", a: "Yes — set custom pricing for bedrooms, living rooms, hallways, and stairs. The booking total calculates automatically." },
      { q: "How do re-booking reminders work?",           a: "Set a re-booking interval (e.g., 12 months). Certxa automatically sends a reminder when it's time for their next cleaning." },
    ],
    testimonial: { quote: "The add-on upsells alone increased my average ticket by $75. Customers just tap to add scotch-guard and I collect more on every job.", name: "Tony V.", business: "Deep Clean Pros", location: "Columbus, OH" },
    compareRows: [
      ["Room-by-room online booking",       true, false],
      ["Add-on upsell during booking",      true, false],
      ["Automatic re-booking reminders",    true, false],
      ["Mobile invoice on arrival",         true, false],
      ["Customer service history",          true, false],
      ["Automated review collection",       true, false],
    ],
  },
  {
    slug: "window-cleaning",
    name: "Window Cleaning",
    emoji: "🪟",
    category: "Cleaning",
    tagline: "Routes. Revenue. Repeat.",
    desc: "Recurring route scheduling, commercial account management, and seasonal re-booking for window cleaning businesses.",
    heroLine1: "Perfect Routes.",
    heroLine2: "Automatic Revenue.",
    badge: "Built for Window Cleaning Businesses",
    features: [
      { icon: "🗺️", title: "Route Planning",              desc: "Organize residential and commercial stops by area. Minimize drive time, maximize jobs per day." },
      { icon: "🏢", title: "Commercial Account Mgmt",     desc: "Track commercial contracts with frequency, pricing, and access instructions per property." },
      { icon: "🔄", title: "Seasonal Re-Booking",         desc: "Auto-send reminders for spring and fall cleanings to keep your recurring clients on the books." },
      { icon: "📸", title: "Before/After Photo Log",      desc: "Document window condition before and after every service. Share with customers for quality assurance." },
    ],
    steps: [
      { num: "01", title: "Book Recurring Clients",  desc: "Set up each customer on their cleaning frequency. Jobs auto-populate your calendar every cycle." },
      { num: "02", title: "Run the Route",            desc: "Your crew starts the day with an optimized route and all job details on their phone." },
      { num: "03", title: "Invoice Automatically",    desc: "Invoices go out the moment a job is marked complete. Customers pay online or by card on-site." },
    ],
    faqs: [
      { q: "Can I manage both residential and commercial accounts?", a: "Yes — Certxa handles both. Commercial accounts have contract pricing, access notes, and billing terms separate from residential." },
      { q: "How do seasonal reminders work?",                         a: "You set the timing (e.g., spring and fall). Certxa automatically contacts all eligible customers with a re-booking link." },
    ],
    testimonial: { quote: "Commercial accounts used to be a spreadsheet nightmare. Now every contract, access code, and billing schedule is in one place.", name: "Rachel K.", business: "ClearView Window Cleaning", location: "Denver, CO" },
    compareRows: [
      ["Route-based scheduling",            true, false],
      ["Commercial contract management",    true, false],
      ["Seasonal re-booking campaigns",     true, false],
      ["Before/after photo documentation",  true, false],
      ["Auto-invoicing on job completion",  true, false],
      ["Automated review requests",         true, false],
    ],
  },
  {
    slug: "pressure-washing",
    name: "Pressure Washing",
    emoji: "💦",
    category: "Cleaning",
    tagline: "Surface by surface. Paid fast.",
    desc: "Online booking by surface type, before/after photos, seasonal packages, and mobile invoicing for pressure washers.",
    heroLine1: "More Jobs.",
    heroLine2: "Less Chasing.",
    badge: "Built for Pressure Washing Businesses",
    features: [
      { icon: "🏠", title: "Surface-Based Booking",      desc: "Customers select surfaces (driveway, deck, siding, roof) when booking. Pricing adjusts automatically." },
      { icon: "📸", title: "Photo Documentation",        desc: "Log before and after photos for every surface cleaned. Share with customers and insurance if needed." },
      { icon: "📦", title: "Seasonal Package Deals",    desc: "Create spring clean or exterior refresh packages. Offer bundled services at a promotional price." },
      { icon: "📱", title: "On-Site Mobile Invoicing",  desc: "Invoice from your truck before you pack up. Collect payment by card or tap-to-pay immediately." },
    ],
    steps: [
      { num: "01", title: "Let Customers Book Online", desc: "They select their surfaces, upload a photo if needed, and pick a time. You see it instantly." },
      { num: "02", title: "Show Up Ready",              desc: "Job details — surfaces, access notes, photos — are on your phone before you arrive." },
      { num: "03", title: "Invoice & Go",               desc: "Send the invoice in 30 seconds. Most customers pay before you leave the driveway." },
    ],
    faqs: [
      { q: "Can I offer bundle pricing?",              a: "Yes — create packages that combine multiple surfaces (e.g., driveway + deck + siding) at a special rate." },
      { q: "How does photo documentation help me?",   a: "Photos show the quality of your work, protect you from disputes, and can be used in marketing with customer permission." },
    ],
    testimonial: { quote: "Customers can book, pay a deposit, and see the before/after photos all without me making a single call. That's how business should work.", name: "Brian L.", business: "PowerBlast Washing Co.", location: "Charlotte, NC" },
    compareRows: [
      ["Surface-based online booking",      true, false],
      ["Before/after photo logging",        true, false],
      ["Seasonal package creation",         true, false],
      ["Deposit collection at booking",     true, false],
      ["Mobile invoicing at job site",      true, false],
      ["Automated review requests",         true, false],
    ],
  },
  {
    slug: "handyman",
    name: "Handyman",
    emoji: "🔨",
    category: "Trades",
    tagline: "Multi-trade. One platform.",
    desc: "Job-site notes, multi-trade service catalog, online booking, and fast invoicing for handymen and tradespeople.",
    heroLine1: "Your Jobs.",
    heroLine2: "All Lined Up.",
    badge: "Built for Handymen & Tradespeople",
    features: [
      { icon: "🛠️", title: "Multi-Trade Catalog",     desc: "List every service you offer — carpentry, drywall, tile, painting — with separate pricing and booking rules." },
      { icon: "📋", title: "Job-Site Notes",            desc: "Add text notes and photos to any job. Pull up what was done at an address on any future visit." },
      { icon: "💰", title: "Hourly or Flat-Rate",       desc: "Bill by the hour or set flat rates per service type. Mix billing modes on a single invoice." },
      { icon: "⭐", title: "Auto Review Requests",     desc: "After every completed job, Certxa texts the customer asking for a Google review — on autopilot." },
    ],
    steps: [
      { num: "01", title: "Set Up Your Services",  desc: "Add every trade you do with pricing. Customers see your full menu when they book online." },
      { num: "02", title: "Get Booked & Show Up",  desc: "Jobs land in your calendar. You get notified. Show up with everything you need on your phone." },
      { num: "03", title: "Invoice on the Spot",   desc: "Tap to build the invoice, collect payment, and send a receipt — all before you pack the truck." },
    ],
    faqs: [
      { q: "Can I handle both small repairs and larger projects?", a: "Yes — Certxa works for one-hour fixes and multi-day jobs. Set different booking types, durations, and billing for each." },
      { q: "How do I track what I did at each property?",          a: "Every job has a notes section for text and photos. Search by address anytime to see the full service history." },
    ],
    testimonial: { quote: "I went from 8 to 22 jobs a week after adding online booking. Customers love being able to book without calling me.", name: "Sam H.", business: "HandyWork Pro", location: "Portland, OR" },
    compareRows: [
      ["Online booking for multiple trades", true, false],
      ["Job-site notes and photos",         true, false],
      ["Hourly and flat-rate billing",      true, false],
      ["Address service history",           true, false],
      ["Automated review collection",       true, false],
      ["SMS reminders to customers",        true, false],
    ],
  },
  {
    slug: "lawn-care",
    name: "Lawn Care",
    emoji: "🌿",
    category: "Outdoor",
    tagline: "Recurring routes. Organized.",
    desc: "Recurring mowing schedules, seasonal contracts, crew dispatch, and route optimization for lawn care businesses.",
    heroLine1: "Your Routes.",
    heroLine2: "Running Like Clockwork.",
    badge: "Built for Lawn Care Businesses",
    features: [
      { icon: "🗓️", title: "Recurring Mow Schedules",   desc: "Set weekly or biweekly mowing routes per customer. Jobs auto-populate every cycle." },
      { icon: "🌾", title: "Seasonal Contract Billing",  desc: "Create spring/summer/fall contracts with auto-billing. Lock in revenue before the season starts." },
      { icon: "🚜", title: "Crew & Equipment Dispatch",  desc: "Assign mowers, trimmers, and blowers to crews. Track what equipment is at which job site." },
      { icon: "🗺️", title: "Route Optimization",        desc: "Organize daily routes by geography. Cut drive time and fit more jobs into every day." },
    ],
    steps: [
      { num: "01", title: "Book Your Season",       desc: "Customers sign up for a season plan or recurring service. Certxa builds the schedule automatically." },
      { num: "02", title: "Dispatch Your Crew",     desc: "Crews start the day with an optimized route, job details, and instructions on their phone." },
      { num: "03", title: "Bill Without Thinking",  desc: "Weekly or monthly billing runs automatically. No invoicing, no calls, no chasing." },
    ],
    faqs: [
      { q: "Can I offer seasonal add-ons like fertilization?", a: "Yes — add spring fertilization, fall aeration, and other seasonal services as add-ons to any plan." },
      { q: "How do I handle rain day reschedules?",             a: "Use the drag-and-drop calendar to reschedule affected jobs. Customers get notified automatically." },
    ],
    testimonial: { quote: "Seasonal contracts changed my cash flow completely. I collect half the season upfront and the billing runs itself.", name: "Kevin O.", business: "Greenside Lawn Co.", location: "Indianapolis, IN" },
    compareRows: [
      ["Recurring mow scheduling",         true, false],
      ["Seasonal contract billing",        true, false],
      ["Crew & equipment dispatch",        true, false],
      ["Route optimization",               true, false],
      ["Automated customer notifications", true, false],
      ["Online new customer booking",      true, false],
    ],
  },
  {
    slug: "snow-removal",
    name: "Snow Removal",
    emoji: "❄️",
    category: "Outdoor",
    tagline: "Storm day ready.",
    desc: "Storm dispatch, seasonal contracts, per-push billing, and route management for snow removal businesses.",
    heroLine1: "Storm Ready.",
    heroLine2: "Every Inch Covered.",
    badge: "Built for Snow Removal Companies",
    features: [
      { icon: "🌨️", title: "Storm-Day Dispatch",       desc: "Activate your entire route with one tap when a storm hits. Every driver gets their jobs instantly." },
      { icon: "📃", title: "Seasonal Contracts",        desc: "Sell unlimited or per-push contracts before the season. Auto-bill and track each agreement." },
      { icon: "📍", title: "Route Management",          desc: "Organize residential and commercial stops into optimized driver routes for each storm event." },
      { icon: "📷", title: "Service Photo Proof",       desc: "Drivers photograph completed properties. You have visual proof of every service rendered." },
    ],
    steps: [
      { num: "01", title: "Sell Contracts Pre-Season", desc: "Offer seasonal and per-push contracts online. Lock in customers before the first snow falls." },
      { num: "02", title: "Activate on Storm Day",      desc: "One tap sends all drivers their routes. Real-time check-ins track progress as they go." },
      { num: "03", title: "Bill Per Push or Monthly",   desc: "Per-push billing runs automatically after each storm. Monthly contracts auto-bill on schedule." },
    ],
    faqs: [
      { q: "How does per-push billing work?",         a: "Mark a property as serviced after each storm event. Certxa calculates the bill and charges the customer automatically." },
      { q: "Can I manage commercial properties too?", a: "Yes — commercial properties have separate route times, access notes, and contract pricing built in." },
    ],
    testimonial: { quote: "We run 85 properties and coordinate 4 drivers. Certxa makes storm days feel like a normal Tuesday — no calls, no chaos.", name: "Ray C.", business: "Arctic Snow Services", location: "Cleveland, OH" },
    compareRows: [
      ["One-tap storm activation",          true, false],
      ["Seasonal contract management",      true, false],
      ["Per-push automatic billing",        true, false],
      ["Driver route management",           true, false],
      ["Photo proof of service",            true, false],
      ["Commercial property support",       true, false],
    ],
  },
  {
    slug: "landscaping",
    name: "Landscaping",
    emoji: "🌳",
    category: "Outdoor",
    tagline: "Design. Install. Repeat.",
    desc: "Project quoting, planting schedules, material tracking, and recurring maintenance billing for landscaping companies.",
    heroLine1: "Beautiful Yards.",
    heroLine2: "Better Cash Flow.",
    badge: "Built for Landscaping Businesses",
    features: [
      { icon: "📐", title: "Project Estimation",       desc: "Build detailed landscape design quotes with plant lists, materials, and labor. Send for digital approval." },
      { icon: "🌱", title: "Planting & Install Logs",  desc: "Record everything installed at a property — plant types, sizes, locations, and care notes." },
      { icon: "🧱", title: "Material Tracking",        desc: "Log mulch, stone, plants, and soil per job. Track what's been used and what's been ordered." },
      { icon: "🔄", title: "Maintenance Plan Billing", desc: "Auto-bill monthly maintenance clients on their plan. No invoicing, no chasing." },
    ],
    steps: [
      { num: "01", title: "Quote the Design",    desc: "Walk the property, build the quote, and send it for approval from your phone. Get a digital signature." },
      { num: "02", title: "Schedule the Install", desc: "Assign crews, order materials, and track progress by phase. Customers get updates as work progresses." },
      { num: "03", title: "Sell a Maintenance Plan", desc: "After the install, offer a monthly maintenance plan. It auto-bills and auto-schedules every month." },
    ],
    faqs: [
      { q: "Can I manage both install and maintenance clients?", a: "Yes — Certxa handles one-time installs and recurring maintenance separately, with their own billing and scheduling." },
      { q: "How do I track plant warranties?",                   a: "Add plant details including purchase date and warranty period to any job record. Get alerts when warranties are about to expire." },
    ],
    testimonial: { quote: "The maintenance plan feature added $8,000 a month in recurring revenue I didn't have before. Customers love the auto-billing.", name: "Priya T.", business: "Greenscapes Design", location: "Scottsdale, AZ" },
    compareRows: [
      ["Landscape design quoting",          true, false],
      ["Plant & material logging",          true, false],
      ["Crew scheduling by phase",          true, false],
      ["Recurring maintenance billing",     true, false],
      ["Customer digital approvals",        true, false],
      ["Automated review collection",       true, false],
    ],
  },
  {
    slug: "tree-service",
    name: "Tree Service",
    emoji: "🌲",
    category: "Outdoor",
    tagline: "Book jobs. Stay safe.",
    desc: "Job site assessments, hazard documentation, crew dispatch, and insurance-ready reports for tree service companies.",
    heroLine1: "Bigger Jobs.",
    heroLine2: "Bigger Revenue.",
    badge: "Built for Tree Service Companies",
    features: [
      { icon: "📋", title: "Job Site Assessment",     desc: "Document tree height, condition, hazards, and access requirements before every job." },
      { icon: "⚠️", title: "Hazard Photo Logging",   desc: "Capture hazard photos for your records and insurance documentation on every job." },
      { icon: "👷", title: "Crew Assignment",         desc: "Send climbers, groundspeople, and chip truck drivers their job details separately." },
      { icon: "🧾", title: "Stump & Disposal Billing", desc: "Bill for tree removal, stump grinding, and wood chip hauling as separate line items on any invoice." },
    ],
    steps: [
      { num: "01", title: "Assess & Quote On-Site",  desc: "Document the job, photograph hazards, and send a professional estimate for customer approval." },
      { num: "02", title: "Dispatch Your Crew",       desc: "Assign each crew role with their specific tasks. Everyone has what they need before they arrive." },
      { num: "03", title: "Invoice Per Service",      desc: "Bill for every service — removal, grinding, hauling — as separate or combined line items." },
    ],
    faqs: [
      { q: "Can I document liability and hazards?", a: "Yes — add hazard notes and photos to every job. These are saved permanently for insurance and legal purposes." },
      { q: "Do you support emergency tree removal?", a: "Yes — flag jobs as emergency, alert on-call crews, and dispatch to site same-day." },
    ],
    testimonial: { quote: "Hazard documentation alone saved us from a dispute that could have cost us $40,000. It's all there in the job photos.", name: "Glenn A.", business: "Summit Tree Service", location: "Seattle, WA" },
    compareRows: [
      ["Job site hazard documentation",     true, false],
      ["Multi-role crew dispatch",          true, false],
      ["Itemized removal/grinding billing", true, false],
      ["Emergency job flagging",            true, false],
      ["Insurance-ready photo logs",        true, false],
      ["Online booking & quoting",          true, false],
    ],
  },
  {
    slug: "junk-removal",
    name: "Junk Removal",
    emoji: "🗑️",
    category: "Cleaning",
    tagline: "Book. Haul. Get paid.",
    desc: "Online booking with volume-based pricing, truck scheduling, and instant invoicing for junk removal businesses.",
    heroLine1: "Full Trucks.",
    heroLine2: "Full Bank Account.",
    badge: "Built for Junk Removal Companies",
    features: [
      { icon: "📦", title: "Volume-Based Pricing",    desc: "Customers select load size (quarter, half, full truck) when booking. Price calculates automatically." },
      { icon: "🚛", title: "Truck & Crew Scheduling", desc: "Assign trucks and crews to jobs. Track capacity and prevent overbooking on any given day." },
      { icon: "♻️", title: "Disposal Tracking",       desc: "Log what was hauled, where it went (donation, recycling, dump), and any fees per job." },
      { icon: "💳", title: "Collect Before You Go",   desc: "Invoice on arrival, collect payment, and mark the job done — all before the truck pulls out." },
    ],
    steps: [
      { num: "01", title: "Let Customers Book Online", desc: "They select load size, upload a photo of the junk, and pick a window. You see it instantly." },
      { num: "02", title: "Send the Truck",              desc: "Your crew gets the job details, address, and load estimate before they leave the depot." },
      { num: "03", title: "Invoice & Drive Away",        desc: "Collect payment on-site via card or tap-to-pay. Receipt goes out automatically." },
    ],
    faqs: [
      { q: "Can customers upload photos of their junk before booking?", a: "Yes — the booking form supports photo uploads so you can see what you're picking up before you arrive." },
      { q: "How do I track truck capacity across multiple jobs?",        a: "The scheduling view shows truck capacity as a progress bar per vehicle per day. Prevent overloading before it happens." },
    ],
    testimonial: { quote: "Volume-based online booking cut our estimate calls by 80%. Customers book themselves, pay online, and we just show up.", name: "Tyrone B.", business: "CleanSweep Junk Removal", location: "Houston, TX" },
    compareRows: [
      ["Online volume-based booking",       true, false],
      ["Pre-job photo upload",              true, false],
      ["Truck capacity management",         true, false],
      ["Disposal destination logging",      true, false],
      ["On-site payment collection",        true, false],
      ["Automated review collection",       true, false],
    ],
  },
  {
    slug: "gutter-cleaning",
    name: "Gutter Cleaning",
    emoji: "🌧️",
    category: "Cleaning",
    tagline: "Seasonal revenue. Automated.",
    desc: "Seasonal re-booking campaigns, online quotes, photo documentation, and quick invoicing for gutter cleaning businesses.",
    heroLine1: "Full Gutters.",
    heroLine2: "Fuller Schedule.",
    badge: "Built for Gutter Cleaning Businesses",
    features: [
      { icon: "🍂", title: "Seasonal Re-Booking",      desc: "Auto-send spring and fall reminders to your past customers. Fill your schedule before it opens." },
      { icon: "📐", title: "Online Quote Requests",    desc: "Customers submit a request with their home size and gutter length. You quote in minutes." },
      { icon: "📸", title: "Before/After Photos",      desc: "Document clogged vs. clear gutters with photos. Share with customers and use in your marketing." },
      { icon: "⚡", title: "Fast Mobile Invoicing",    desc: "Send an invoice from the truck before you pack up. Most customers pay on the spot." },
    ],
    steps: [
      { num: "01", title: "Capture Leads Seasonally",  desc: "Your re-booking campaign fires automatically. Past customers receive a reminder with a booking link." },
      { num: "02", title: "Schedule & Show Up",         desc: "Jobs land in your calendar with address, gutter notes, and access details ready to go." },
      { num: "03", title: "Invoice & Collect On-Site",  desc: "Invoice takes 30 seconds. Accept card, cash, or tap-to-pay before leaving the job." },
    ],
    faqs: [
      { q: "How many re-booking reminders can I send?", a: "As many as you want. Set them by season or time since last service. Certxa handles the outreach automatically." },
      { q: "Can I upsell gutter guard installation?",   a: "Yes — add gutter guard as an add-on in your booking flow. Customers can select it during their service booking." },
    ],
    testimonial: { quote: "My fall season books up two weeks before I even start. The seasonal reminders fill my calendar on autopilot.", name: "Nicole H.", business: "ClearFlow Gutter Pros", location: "Cincinnati, OH" },
    compareRows: [
      ["Seasonal re-booking campaigns",     true, false],
      ["Online quote request form",         true, false],
      ["Before/after photo logging",        true, false],
      ["Gutter guard add-on upsell",        true, false],
      ["On-site mobile invoicing",          true, false],
      ["Automated review requests",         true, false],
    ],
  },
  {
    slug: "painting",
    name: "Painting",
    emoji: "🎨",
    category: "Specialty",
    tagline: "Quote it. Paint it. Collect.",
    desc: "Detailed estimates with color notes, project milestones, crew scheduling, and deposit billing for painting contractors.",
    heroLine1: "More Estimates Won.",
    heroLine2: "More Projects Done.",
    badge: "Built for Painting Contractors",
    features: [
      { icon: "🖌️", title: "Detailed Estimate Builder",   desc: "Build estimates with surface measurements, paint brand, color codes, and labor — room by room." },
      { icon: "🎨", title: "Color & Finish Notes",        desc: "Record paint color codes, finish type, and brand per surface. Reference anytime for touch-ups." },
      { icon: "👷", title: "Multi-Crew Project Tracking", desc: "Assign interior and exterior crews to separate portions of the same job with independent schedules." },
      { icon: "💰", title: "Deposit + Progress Billing",  desc: "Collect a deposit to start, then bill at milestones or on completion. All tracked and automated." },
    ],
    steps: [
      { num: "01", title: "Build the Estimate",     desc: "Walk the job, take measurements, note colors, and send a branded estimate for digital approval." },
      { num: "02", title: "Schedule the Crew",      desc: "Assign painters to interior, exterior, or specific rooms. Set start dates and daily task notes." },
      { num: "03", title: "Collect in Milestones",  desc: "Request a deposit to start, then bill progress or final payments automatically at each stage." },
    ],
    faqs: [
      { q: "Can I save paint specs for future touch-ups?", a: "Yes — color code, sheen level, and brand are saved to every surface you paint. Pull them up instantly for any re-order or touch-up." },
      { q: "How does multi-crew scheduling work?",          a: "Assign separate crews to separate phases. Each painter sees only their portion, timeline, and task notes." },
    ],
    testimonial: { quote: "The estimate builder is so fast now. I spend 20 minutes on a quote that used to take two hours. And I close them faster because they look professional.", name: "Marco D.", business: "ColorCraft Painting", location: "Miami, FL" },
    compareRows: [
      ["Room-by-room estimate builder",     true, false],
      ["Paint color & brand record",        true, false],
      ["Multi-crew scheduling",             true, false],
      ["Deposit + progress billing",        true, false],
      ["Digital estimate approval",         true, false],
      ["Automated review requests",         true, false],
    ],
  },
  {
    slug: "appliance-repair",
    name: "Appliance Repair",
    emoji: "🔌",
    category: "Trades",
    tagline: "Diagnose. Fix. Invoice.",
    desc: "Parts inventory, warranty tracking, same-day booking, and itemized invoicing for appliance repair businesses.",
    heroLine1: "Faster Repairs.",
    heroLine2: "Faster Payments.",
    badge: "Built for Appliance Repair Technicians",
    features: [
      { icon: "🔩", title: "Parts Inventory Tracking",   desc: "Log parts on hand. Add parts to jobs from your inventory and track what needs reordering." },
      { icon: "🔧", title: "Repair & Diagnosis Notes",   desc: "Record appliance make, model, error code, and repair notes per visit for a full service history." },
      { icon: "📋", title: "Warranty & Guarantee Logs",  desc: "Track parts and labor warranties per repair. Send automatic reminders when warranties expire." },
      { icon: "📱", title: "Same-Day Online Booking",    desc: "Customers book urgent repairs online for same or next-day service. You get notified instantly." },
    ],
    steps: [
      { num: "01", title: "Accept the Booking",    desc: "Customers book online for same-day or scheduled service. You see the appliance type and issue description." },
      { num: "02", title: "Diagnose & Fix",        desc: "Log the make, model, error, parts used, and repair notes right from your phone during the visit." },
      { num: "03", title: "Invoice with Warranty", desc: "Invoice on the spot with parts, labor, and warranty terms. Customers get a receipt and warranty record." },
    ],
    faqs: [
      { q: "Can I track which parts I use most?",         a: "Yes — your parts inventory shows usage history. Reorder alerts fire when stock drops below your threshold." },
      { q: "How do warranty reminders work?",              a: "Set a warranty period (e.g., 90 days on parts) when invoicing. Certxa reminds you and the customer before it expires." },
    ],
    testimonial: { quote: "Parts tracking alone saved me $600 last month. I stopped double-buying because I now know exactly what's in my van.", name: "Dion F.", business: "QuickFix Appliance Repair", location: "Baltimore, MD" },
    compareRows: [
      ["Parts inventory tracking",          true, false],
      ["Appliance model & error logging",   true, false],
      ["Parts + labor warranty records",    true, false],
      ["Same-day online booking",           true, false],
      ["Itemized repair invoicing",         true, false],
      ["Automated review collection",       true, false],
    ],
  },
  {
    slug: "garage-door",
    name: "Garage Door",
    emoji: "🚗",
    category: "Trades",
    tagline: "Install. Repair. Bill fast.",
    desc: "Same-day dispatch, parts tracking, service history per door, and quick invoicing for garage door companies.",
    heroLine1: "Every Door.",
    heroLine2: "Every Customer.",
    badge: "Built for Garage Door Companies",
    features: [
      { icon: "🚨", title: "Same-Day Emergency Dispatch", desc: "Flag urgent calls and route to the nearest tech. Customers get an ETA text immediately." },
      { icon: "📋", title: "Door & Opener History",      desc: "Record make, model, spring type, and service history per door. Know exactly what's there before you arrive." },
      { icon: "🔩", title: "Parts Inventory",            desc: "Track springs, cables, openers, and panels in your van inventory. Log usage per job automatically." },
      { icon: "💳", title: "Invoice Before You Leave",   desc: "Build a parts + labor invoice on-site and collect payment by card, cash, or tap-to-pay." },
    ],
    steps: [
      { num: "01", title: "Capture Every Call",   desc: "Online or phone bookings go straight into your dispatch queue. No calls missed, no leads lost." },
      { num: "02", title: "Dispatch Your Tech",   desc: "Assign the job, pull up door history, and get your tech to the site with everything they need." },
      { num: "03", title: "Invoice & Collect",    desc: "Invoice with parts and labor on-site. Get paid before you drive away." },
    ],
    faqs: [
      { q: "Can I track different door types?",      a: "Yes — log opener brand, spring type, door model, and color for each customer. It's all there for every service call." },
      { q: "Do you support commercial garage doors?", a: "Yes — Certxa handles both residential and commercial with separate pricing, access notes, and billing." },
    ],
    testimonial: { quote: "The door history feature is a must. I know exactly what spring type a customer has before I even open my van.", name: "Frank P.", business: "A1 Garage Door Solutions", location: "Las Vegas, NV" },
    compareRows: [
      ["Emergency same-day dispatch",       true, false],
      ["Door & opener model history",       true, false],
      ["Parts inventory per vehicle",       true, false],
      ["On-site parts + labor invoicing",   true, false],
      ["Commercial property support",       true, false],
      ["Automated review requests",         true, false],
    ],
  },
  {
    slug: "chimney",
    name: "Chimney Service",
    emoji: "🏚️",
    category: "Specialty",
    tagline: "Inspect. Clean. Certify.",
    desc: "Inspection reports, code compliance notes, photo documentation, and annual re-booking for chimney service companies.",
    heroLine1: "Every Inspection.",
    heroLine2: "Fully Documented.",
    badge: "Built for Chimney Service Companies",
    features: [
      { icon: "📋", title: "CSIA Inspection Reports",  desc: "Build Level 1, 2, and 3 inspection reports digitally. Email to customers and attach to the job record." },
      { icon: "📸", title: "Interior Photo Logging",   desc: "Document creosote buildup, cracks, and blockages with photos. All stored to the chimney's history." },
      { icon: "📜", title: "Code Compliance Notes",    desc: "Record findings by NFPA code, note required repairs, and flag priority safety items per inspection." },
      { icon: "🔁", title: "Annual Re-Booking",        desc: "Auto-remind customers when their annual cleaning is due. Fill your fall schedule before you open it." },
    ],
    steps: [
      { num: "01", title: "Book the Inspection",    desc: "Customers book inspections online. You see the address, chimney type, and last service date." },
      { num: "02", title: "Inspect & Document",     desc: "Work through the inspection on your phone. Add photos, code notes, and findings as you go." },
      { num: "03", title: "Deliver the Report",     desc: "Send a professional inspection report by email in seconds. Collect payment from the same screen." },
    ],
    faqs: [
      { q: "Can I deliver digital inspection reports?",  a: "Yes — build the report on-site and send a PDF to the customer immediately after the inspection." },
      { q: "How do I manage seasonal volume?",           a: "The annual re-booking reminders fill your fall calendar automatically, spreading the load before demand peaks." },
    ],
    testimonial: { quote: "Digital inspection reports doubled our repair conversions. Customers see the photos and the code violations right there on their phone.", name: "Barb N.", business: "HearthPro Chimney Service", location: "Boston, MA" },
    compareRows: [
      ["Digital inspection report builder", true, false],
      ["Interior chimney photo logging",    true, false],
      ["NFPA code note documentation",      true, false],
      ["Annual re-booking campaigns",       true, false],
      ["Online inspection booking",         true, false],
      ["Automated review requests",         true, false],
    ],
  },
  {
    slug: "moving",
    name: "Moving",
    emoji: "📦",
    category: "Specialty",
    tagline: "Quote. Load. Collect.",
    desc: "Online quote requests, multi-crew dispatch, truck scheduling, and deposit billing for moving companies.",
    heroLine1: "More Moves.",
    heroLine2: "More Revenue.",
    badge: "Built for Moving Companies",
    features: [
      { icon: "📐", title: "Online Quote Requests",   desc: "Customers submit move details — bedrooms, distance, floor — and get a quoted range instantly." },
      { icon: "🚛", title: "Truck & Crew Scheduling", desc: "Assign trucks and crew by move size. Track vehicle capacity and crew availability in one view." },
      { icon: "📋", title: "Inventory Checklist",     desc: "Build a pre-move item list so your crew knows exactly what's being moved before they arrive." },
      { icon: "💰", title: "Deposit + Final Billing", desc: "Collect a booking deposit upfront. Bill the balance on move-out day. All tracked and automated." },
    ],
    steps: [
      { num: "01", title: "Get the Quote Request",   desc: "Customer fills out the move details online. You confirm and send a deposit invoice to lock the date." },
      { num: "02", title: "Dispatch Your Crew",       desc: "Assign trucks, crew, and any specialty equipment. Everyone gets job details on their phone." },
      { num: "03", title: "Collect on Move Day",      desc: "Bill the remaining balance on move day. Accept card, cash, or bank transfer on-site." },
    ],
    faqs: [
      { q: "Can I handle long-distance moves?",    a: "Yes — Certxa supports any service area. Set distance-based pricing tiers for local vs. long-distance moves." },
      { q: "How do I track truck availability?",   a: "The scheduling view shows each truck's bookings per day. Prevent overbooking before it happens." },
    ],
    testimonial: { quote: "Deposits are now collected automatically when someone books. We stopped having cancellations because customers have skin in the game.", name: "Elena G.", business: "Swift Movers LLC", location: "San Diego, CA" },
    compareRows: [
      ["Online move quote requests",        true, false],
      ["Truck + crew scheduling",           true, false],
      ["Pre-move inventory checklist",      true, false],
      ["Deposit + balance billing",         true, false],
      ["Distance-based pricing tiers",      true, false],
      ["Automated review collection",       true, false],
    ],
  },
  {
    slug: "general-contracting",
    name: "General Contracting",
    emoji: "🏗️",
    category: "Trades",
    tagline: "Manage every phase.",
    desc: "Project estimation, subcontractor management, milestone billing, and full job tracking for general contractors.",
    heroLine1: "Every Project.",
    heroLine2: "Fully Under Control.",
    badge: "Built for General Contractors",
    features: [
      { icon: "📐", title: "Project Estimation",       desc: "Build detailed project quotes with labor, materials, permits, and subcontractor costs." },
      { icon: "👷", title: "Subcontractor Scheduling", desc: "Add subs to your projects. Assign phases, set schedules, and track their progress independently." },
      { icon: "💰", title: "Milestone-Based Billing",  desc: "Bill at each project phase — foundation, framing, finish. Cash flow matches the work done." },
      { icon: "📋", title: "Change Order Management", desc: "Log change orders with customer approval. Keep your contract amount accurate as scope evolves." },
    ],
    steps: [
      { num: "01", title: "Quote & Win the Job",      desc: "Build a full project estimate and send for digital approval. Get a signed agreement on the spot." },
      { num: "02", title: "Manage the Build",         desc: "Assign your team and subs by phase. Track progress, issues, and completions in real time." },
      { num: "03", title: "Bill Per Milestone",        desc: "Request payment at each phase. Customers pay on time because they see the progress clearly." },
    ],
    faqs: [
      { q: "How do I manage change orders?",           a: "Log any scope change, get customer approval digitally, and the invoice updates automatically to reflect the new total." },
      { q: "Can I track subcontractor payments?",      a: "Yes — record payments to subs per phase. See your net margin per project after all costs." },
    ],
    testimonial: { quote: "Milestone billing changed everything. I used to float jobs for 60 days. Now I bill every phase and my cash flow is finally healthy.", name: "Andre M.", business: "Meridian Construction", location: "Austin, TX" },
    compareRows: [
      ["Full project estimation",           true, false],
      ["Subcontractor phase scheduling",    true, false],
      ["Milestone billing automation",      true, false],
      ["Change order with approval",        true, false],
      ["Sub payment tracking",              true, false],
      ["Digital contract signing",          true, false],
    ],
  },
  {
    slug: "flooring",
    name: "Flooring",
    emoji: "🪵",
    category: "Specialty",
    tagline: "Quote by sq ft. Install fast.",
    desc: "Square footage estimating, material tracking, install scheduling, and deposit billing for flooring companies.",
    heroLine1: "Every Floor Quoted.",
    heroLine2: "Every Job Paid.",
    badge: "Built for Flooring Contractors",
    features: [
      { icon: "📐", title: "Square Footage Estimating", desc: "Input room dimensions and Certxa calculates material quantity and pricing automatically." },
      { icon: "🪵", title: "Material & Order Tracking",  desc: "Log flooring type, grade, color, and order status. Know when materials arrive before the install date." },
      { icon: "🗓️", title: "Install Day Scheduling",     desc: "Schedule install crews per room or floor. Set prep, install, and finishing as separate tasks." },
      { icon: "💳", title: "Deposit + Final Payment",    desc: "Collect a material deposit upfront, then final payment after install. All automated." },
    ],
    steps: [
      { num: "01", title: "Measure & Quote",      desc: "Enter room dimensions, select flooring type, and send a professional estimate in minutes." },
      { num: "02", title: "Order & Schedule",     desc: "Track material orders and schedule the install crew once materials are confirmed." },
      { num: "03", title: "Collect Both Payments", desc: "Material deposit on order, final balance on completion. Both tracked and sent automatically." },
    ],
    faqs: [
      { q: "Can I handle both hardwood and tile?", a: "Yes — set up separate service types with their own pricing, material lists, and install timelines." },
      { q: "How do I track material orders?",       a: "Log the order date, supplier, and expected arrival. Get notified when to follow up if materials are delayed." },
    ],
    testimonial: { quote: "The square footage estimator cut my quote time from 45 minutes to under 10. And it's more accurate because the math is automatic.", name: "Yolanda B.", business: "Premier Floors Co.", location: "Charlotte, NC" },
    compareRows: [
      ["Square footage estimation",         true, false],
      ["Material order tracking",           true, false],
      ["Install crew scheduling",           true, false],
      ["Deposit + final billing",           true, false],
      ["Multi-material type support",       true, false],
      ["Automated review requests",         true, false],
    ],
  },
  {
    slug: "drywall",
    name: "Drywall",
    emoji: "🧱",
    category: "Specialty",
    tagline: "Quote. Hang. Invoice.",
    desc: "Sheet-count estimating, material tracking, crew scheduling, and quick invoicing for drywall contractors.",
    heroLine1: "Every Project.",
    heroLine2: "Priced Right.",
    badge: "Built for Drywall Contractors",
    features: [
      { icon: "📐", title: "Sheet-Count Estimation",   desc: "Calculate drywall sheets needed from room dimensions. Quote materials and labor in minutes." },
      { icon: "🧱", title: "Material Tracking",        desc: "Log sheets, compound, tape, and screws per job. Track what's used and what's left." },
      { icon: "👷", title: "Crew Day Scheduling",      desc: "Assign crew members to hang, tape, mud, and sand on separate days. Track each phase's completion." },
      { icon: "💰", title: "Progress Invoicing",       desc: "Bill for hang, tape, and finish as separate milestones. Collect payment at each stage." },
    ],
    steps: [
      { num: "01", title: "Estimate the Job",      desc: "Enter room count and square footage. Get a sheet count, material list, and labor estimate instantly." },
      { num: "02", title: "Schedule by Phase",     desc: "Break the job into hang, tape/mud, and sand/finish phases. Assign crew to each day." },
      { num: "03", title: "Invoice Each Phase",    desc: "Bill as each phase completes. Customers see the progress and pay along the way." },
    ],
    faqs: [
      { q: "Can I quote commercial drywall jobs?",    a: "Yes — Certxa handles both residential and light commercial with separate pricing scales and billing rules." },
      { q: "How do I track material waste?",           a: "Log actual vs. estimated sheets used per job. Over time you'll see patterns that help you quote more accurately." },
    ],
    testimonial: { quote: "Progress billing means I never wait 60 days for a full payment. I bill after hang, after mud, after finish. Cash flow is totally different now.", name: "Luis R.", business: "SmoothWall Drywall", location: "Sacramento, CA" },
    compareRows: [
      ["Sheet-count auto-estimation",       true, false],
      ["Per-phase crew scheduling",         true, false],
      ["Material tracking per job",         true, false],
      ["Progress milestone billing",        true, false],
      ["Commercial + residential support",  true, false],
      ["Automated review requests",         true, false],
    ],
  },
];

export const PRO_CATEGORIES: { label: string; value: ProIndustry["category"] }[] = [
  { label: "Trades & Contracting", value: "Trades" },
  { label: "Cleaning Services",    value: "Cleaning" },
  { label: "Outdoor & Lawn",       value: "Outdoor" },
  { label: "Specialty Services",   value: "Specialty" },
];

export function getProIndustry(slug: string): ProIndustry | undefined {
  return PRO_INDUSTRIES.find(i => i.slug === slug);
}
