// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mobile-booking/Confirm.tsx": () => import("../components/mockups/mobile-booking/Confirm.tsx"),
  "./components/mockups/mobile-booking/DateTime.tsx": () => import("../components/mockups/mobile-booking/DateTime.tsx"),
  "./components/mockups/mobile-booking/Services.tsx": () => import("../components/mockups/mobile-booking/Services.tsx"),
  "./components/mockups/mobile-booking/Success.tsx": () => import("../components/mockups/mobile-booking/Success.tsx"),
  "./components/mockups/mobile-booking/Welcome.tsx": () => import("../components/mockups/mobile-booking/Welcome.tsx")
};
